### ISSUE TITLE
Migrate to new file format

### ISSUE THREAD

**Issue by dantrevino** [boomcrypto/NoteRiot#21]
This process is only relevent on `note.riot.ai` ... and for the "import" function on `noteriot.app` ... 

Additionally, while the new format is more robust, it will only help loading performance for users with *many* large notes.  Users with many small notes gain some robustness, but will not see any loading performance increase.

## Files
`riotnotes.json` <-- original file
`migrated.json`
```
{
status: true,
date: datetime,
log: uri,
backup: uri
} 
```
`index.json`
```
{
 id: xxx-yyy-zzz
 preview: string (120),
 img: note.attachments[0],
 fave: note.fave,
 trash: note.trash,
 color: note.color
 tags: note.tags
 modified: note.modified
}
```
`notes/xxx-yyy-zzz.json` <--- existing note format
`migration-errors.json` 
```
{ 
 id: xxx-yyy-zzz
error: error msg
}
```

## tasks

- [ ]  implement migration & create new files

1. backup to `backups/YYYYMMDD-riotnotes.json`
1. read & parse riotnotes.json
1. For each note:
    -- create `notes/xxx-yyy-zzz.json`
    -- append xxx-yyy-zzz to `index.json`
  
- [ ]  update existing actions
__`addNote()`__
- add notes/xxx-yyy-zzz.json
- add to index.json

__`updateNote()`__
- update `notes/xxx-yyy-zzz.json`
- if preview text has changed, update `index.json`

__`fetchData()`__
- if `index.json` exists follow new loading format
  -- load previews from `index.json`
  -- on note load/edit, load full note from `notes/xxx-yyy-zzz.json`
- else do migration

- [ ]  create new actions
__`getNoteById()`__ 
// used when note is opened in the editor
- getFile('notes/xxx-yyy-zzz.json')
- parse note

__`deleteNoteById()`__
// used when 'delete permanently' option is used
- delete `notes/xxx-yyy-zzz.json`
- remove xxx-yyy-zzz from `index.json`
